import type { Metadata } from "next";
import SiteNav from "@/components/SiteNav";
import SiteFooter from "@/components/SiteFooter";

export const metadata: Metadata = {
  title: "Terms of Service — InsightsTube",
  description: "The terms that apply when you use InsightsTube's free YouTube transcript and AI summary tools.",
  alternates: { canonical: "/terms" },
};

export default function Terms() {
  return (
    <>
      <SiteNav />
      <main className="page">
        <h1>Terms of Service</h1>
        <p className="page-sub">Last updated: June 12, 2026</p>

        <p>
          By using insightstube.com (the &quot;Service&quot;) you agree to these terms.
          If you don&apos;t agree, please don&apos;t use the Service.
        </p>

        <h2>What the Service does</h2>
        <p>
          InsightsTube retrieves the publicly available caption tracks of YouTube
          videos and presents them as transcripts, subtitle files and AI-generated
          summaries. The Service does not download, copy, store or distribute video or
          audio content.
        </p>

        <h2>Acceptable use</h2>
        <ul>
          <li>Use the tools for personal study, research, accessibility, citation and similar fair purposes.</li>
          <li>Respect the rights of content creators. The transcript text belongs to the video&apos;s owner; you are responsible for how you use it.</li>
          <li>No automated scraping, bulk harvesting or abuse of the Service. We may rate-limit or block traffic that threatens availability for others.</li>
        </ul>

        <h2>AI-generated content</h2>
        <p>
          Summaries and takeaways are generated by an AI model from the transcript.
          They may contain inaccuracies and are provided for convenience only — always
          verify important claims against the original video.
        </p>

        <h2>No warranty</h2>
        <p>
          The Service is provided &quot;as is&quot;, free of charge, without warranties
          of any kind. Caption availability depends entirely on YouTube and the video
          owner; we cannot guarantee that any video has a retrievable transcript, or
          that the Service will be uninterrupted or error-free.
        </p>

        <h2>Limitation of liability</h2>
        <p>
          To the maximum extent permitted by law, InsightsTube shall not be liable for
          any indirect, incidental or consequential damages arising from the use of
          the Service.
        </p>

        <h2>Third parties</h2>
        <p>
          YouTube is a trademark of Google LLC. InsightsTube is not affiliated with,
          endorsed by or sponsored by YouTube or Google. Your use of YouTube content
          remains subject to YouTube&apos;s own Terms of Service.
        </p>

        <h2>Changes</h2>
        <p>
          We may update these terms; the date above reflects the latest revision.
          Continued use of the Service after changes means you accept the updated terms.
        </p>

        <p>
          Questions? <a href="mailto:info@insightstube.com">info@insightstube.com</a>
        </p>
      </main>
      <SiteFooter />
    </>
  );
}
